### ISSUE TITLE
Billing service + billing permission

### ISSUE THREAD

**Issue by Palid** [rosenpin/notifications-for-pokemon-go#1]
Hey,
Love your project, but got one simple question:
Why do you have a billing permissions and billing service created in code if you don't need to use it?
https://github.com/rosenpin/notifications-for-pokemon-go/blob/master/app/src/main/java/com/tomer/poke/notifier/MainActivity.java#L55

**Comment by rosenpin** [comment]
I've added an option to support the development in the latest version.

It shouldn't change anything about the app.
