### ISSUE TITLE
Bug reporting should not include user email

### ISSUE THREAD

**Issue by chalkos** [rosenpin/notifications-for-pokemon-go#6]
I like the idea of reporting bugs automatically providing some of the phone specs, but I don't think that posting the sender email in the issue description raises some privacy issues.

You could try to use the email address to send an email informing the user that an issue was created and providing a link to the issue. Or save it internally and send an email once the issue is closed.

**Comment by rosenpin** [comment]
I'm using this [library](https://github.com/HeinrichReimer/android-issue-reporter) to do it, it's not flexible enough to do it.

I have no way to save the user email without showing it on Github, I don't have a private server/database so I can't save it there either.

I have to ask for emails so I can contact users directly if needed.

If you have any suggestion for me I'll be glad to use it.

**Comment by chalkos** [comment]
You seem to have an active fork of that project, maybe you could change the code to just don't ask for an email or include something like "this will be public on github" (I don't know if you already do this as I have not tried the app yet).

To save user email, there are some free databases around (google it) or you could try to send the email/issue pairs to a google drive spreadsheet or form... This would include some work on the issue reporting system ofc. There don't seem to be better options without some work on a bug reporting system... you could also send yourself an email with this info, although it kind of goes against the library's punch line: "Is your Inbox full of bug reports and requests from your users?"

you could manually edit the issue descriptions, manually removing the email and associating it locally in some kind of database (google/excel spreadsheet?).

I'm afraid all I have to offer for now are ideas :)

**Comment by Palid** [comment]
@rosenpin Use heroku for that for free database, Firebase or other SaaSes.

**Comment by rosenpin** [comment]
@chalkos
Thank you for all of the suggestions.
I understand what you are saying, but I would really prefer to just spend more time working on the app instead of a robust reporting system (although it could be useful later).
For now, I'll just make the email field optional and push an update later today.

**Comment by rosenpin** [comment]
BTW, thanks for taking interest in the app and contacting me :)
I appreciate it.
